spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: clinic-management-system
  datasource:
    url: jdbc:mysql://localhost:3306/clinic_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    view:
      prefix: /templates/
      suffix: .html

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: java.text.SimpleDateFormat
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html