name: Build and Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/clinic-management-system:latest
            ${{ secrets.DOCKER_USERNAME }}/clinic-management-system:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop clinic-app || true
            docker rm clinic-app || true
            
            docker rmi ${{ secrets.DOCKER_USERNAME }}/clinic-management-system:latest || true
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/clinic-management-system:latest
            
            docker run -d \
              --name clinic-app \
              --restart unless-stopped \
              -p 8080:8080 \
              -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
              -e MYSQL_DB=${{ secrets.MYSQL_DB }} \
              -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
              -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/clinic-management-system:latest
            
            echo "Deployment completed! Checking logs..."
            sleep 10
            docker logs --tail 50 clinic-app